# kubectl get clusterrolebinding -A
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ .Values.app }}
    component: {{ .Values.targetAllocator.component }}
  name: {{ .Values.targetAllocator.clusterRoleBinding.base }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.targetAllocator.clusterRole.base }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.targetAllocator.serviceAccount }}
    namespace: {{ .Values.namespace}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ .Values.app }}
    component: {{ .Values.targetAllocator.component }}
  name: {{ .Values.targetAllocator.clusterRoleBinding.monitor }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.targetAllocator.clusterRole.monitor }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.targetAllocator.serviceAccount }}
    namespace: {{ .Values.namespace}}
