# https://github.com/open-o11y/prometheus-sample-app/blob/master/prometheus-sample-app-k8s-deployment.yaml
# https://gallery.ecr.aws/g0z4v6x0/prometheus-sample-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-sample-app-deployment
  namespace: {{ .Values.namespace }}
  annotations:
    sidecar.opentelemetry.io/inject: "true"
spec:
  selector:
    matchLabels:
      app: prometheus-sample-app
  replicas: 1 # tells deployment to run 5 pods matching the template
  template:
    metadata:
      labels:
        app: prometheus-sample-app
      annotations:
        prometheus.io/scrape: "true"
        sidecar.opentelemetry.io/inject: "true"
        #sidecar.opentelemetry.io/inject: {{ .Values.sidecar.name }}
    spec:
      containers:
        - name: prometheus-sample-app
          image: public.ecr.aws/g0z4v6x0/prometheus-sample-app:latest
          imagePullPolicy: Never
          command:
            - "/bin/main"
          args:
            - "--metric_count=1"
          ports:
            - containerPort: 8080

## HELP test_counter0 This is my counter
## TYPE test_counter0 counter
#test_counter0 3695.096536922902
## HELP test_gauge0 This is my gauge
## TYPE test_gauge0 gauge
#test_gauge0 3709.1382294084347
## HELP test_histogram0 This is my histogram
## TYPE test_histogram0 histogram
#test_histogram0_bucket{le="0.005"} 35
#test_histogram0_bucket{le="0.1"} 4621
#test_histogram0_bucket{le="1"} 716827
#test_histogram0_bucket{le="+Inf"} 716827
#test_histogram0_sum 482587.241945764
#test_histogram0_count 716827
## HELP test_summary0 This is my summary
## TYPE test_summary0 summary
#test_summary0{quantile="0.1"} 0.999391166377522
#test_summary0{quantile="0.5"} 0.999391166377522
#test_summary0{quantile="0.99"} 0.999391166377522
#test_summary0_sum 482587.241945764
#test_summary0_count 716827
