# kubectl get serviceaccount -A
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Values.app }}
    component: {{ .Values.targetAllocator.component }}
  name: {{ .Values.targetAllocator.serviceAccount }}
  namespace: {{ .Values.namespace }}
