# kubectl get servicemonitor -A
#---
#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  labels:
#    app: {{ .Values.app }}
#    component: {{ .Values.targetAllocator.component }}
#  name: {{ .Values.serviceMonitor.name }}
#  namespace: {{ .Values.namespace }}
#spec:
#  selector:
#    matchLabels:
#      app_kubernetes_io_component: {{ .Values.targetAllocator.component }}
#      app_kubernetes_io_name: {{ .Values.targetAllocator.name }}
#  namespaceSelector:
#    #any: true
#    matchNames:
#    - {{ .Values.namespace }}
#
#  endpoints:
#  - interval: {{ .Values.serviceMonitor.interval }}
#    port: "{{ .Values.serviceMonitor.port }}"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
spec:
  endpoints:
    - interval: 30s
      targetPort: 8080
      path: /metrics
  selector:
    matchLabels:
      app_kubernetes_io_name: kube-state-metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
spec:
  endpoints:
    - interval: 30s
      targetPort: 9402
      path: /metrics
  selector:
    matchLabels:
      app: cert-manager
